### ISSUE TITLE
NYU test set predictions

### ISSUE THREAD

**Issue by shariqfarooq123** [wl-zhao/VPD#1]
Hi, 
Thanks for sharing your work! It's an exciting result. 
Could you please share the predictions on NYU-Depth v2 in raw 16-bit PNG format for easy comparison? Thanks

**Comment by lzy-19** [comment]
Hi,
Thanks for your interest in our work and the advice. We have updated our code and README.md for visualizations in raw 16-bit PNG. We provide the results of VPD [here](https://cloud.tsinghua.edu.cn/f/27354f47ba424bb3ad40/?dl=1).

**Comment by shariqfarooq123** [comment]
awesome, thanks!
