### ISSUE TITLE
Cross-Attention maps

### ISSUE THREAD

**Issue by Frankyang108** [wl-zhao/VPD#12]
How to visualize Cross-Attention Maps for text prompts in fig1 (b)?

Hi, I would like to ask how to visualize prompts for a given picture using VPD, could you please help me with it?

**Comment by wl-zhao** [comment]
Hi, the visualization code is from [Prompt-to-Prompt](https://github.com/google/prompt-to-prompt), please refer to their repo for detailed instructions.

Please also feel free to ask here if there is still any trouble.

**Comment by OrangeSodahub** [comment]
@wl-zhao Hi, could you please specify which file/line it is?

**Comment by wl-zhao** [comment]
See [here](https://github.com/google/prompt-to-prompt/blob/main/prompt-to-prompt_stable.ipynb)
