### ISSUE TITLE
how can i get the depth metrics in this paper?

### ISSUE THREAD

**Issue by jisu9867** [wl-zhao/VPD#15]
Hi. Thanks for sharing this code and good paper.

recently. I would like to get depth estimation metrics using a pretrained model(vpd_depth_480x480.pth).
but when i evaluated the  pretrained model these error messages came out.

Unexpected Keys: ['model_ema.decay', 'model_ema.num_updates']
Traceback (most recent call last):
  File "test.py", line 173, in <module>
    main()
  File "test.py", line 47, in main
    model.load_state_dict(model_weight, strict=False)
  File "/home/jslee/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VPDDepth:
	size mismatch for decoder.deconv_layers.3.weight: copying a param with shape torch.Size([32, 32, 2, 2]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).
	size mismatch for decoder.deconv_layers.6.weight: copying a param with shape torch.Size([32, 32, 2, 2]) from checkpoint, the shape in current model is torch.Size([32, 32, 4, 4]).

what's my problem? Why are the pretrained weights different from the NYU input images?

**Comment by cvrookieytd** [comment]
Hello, have you managed to reproduce it?

**Comment by cvrookieytd** [comment]
I met some problems in the process of reproducing, could I communicate with you?

**Comment by wl-zhao** [comment]
It looks like something is wrong with the `deconv kernels`. We have specified the `--deconv_kernels` [here](https://github.com/wl-zhao/VPD/blob/60f18526c44ac6e23a75bb87dd21d11ea70d406a/depth/test.sh#LL5C48-L5C48), maybe you should have a check.

**Comment by jisu9867** [comment]
you're right. 
When I changed it to Kernel[2, 2, 2] in code, I was able to get the metrics
thanks you!

**Comment by jisu9867** [comment]
> I met some problems in the process of reproducing, could I communicate with you?

sure

**Comment by cvrookieytd** [comment]
In inference.yaml, 
cond_stage_config:
target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
But in the LDM. Modules. The encoders. Modules
How did you solve the FrozenCLIPEmbedder function?

**Comment by cvrookieytd** [comment]
> > I met some problems in the process of reproducing, could I communicate with you?
> 
> sure

In inference.yaml,
cond_stage_config:
target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
But in the LDM. Modules. The encoders. Modules
How did you solve the FrozenCLIPEmbedder function?
