### ISSUE TITLE
An error in dump_nyu_text_embeddings file

### ISSUE THREAD

**Issue by aiforworlds** [wl-zhao/VPD#17]
There are errors in this file VPD/depth/dump_nyu_text_embeddings  line 14,
from clip import FrozenCLIPEmbedderContext
There is no corresponding function FrozenCLIPEmbedderContext in the https://github.com/openai/CLIP.git
In stablediffusion github used FrozenCLIPTextEmbedder to realize encoder for text
So I want to know if there's an error in this code Thank you very much

**Comment by aiforworlds** [comment]
Using the code dump_nyu_text_embeddings.py， The result would have a shape zeroshot_weights.shape=[27, 1, 768]， This is different from the nyu_class_embeddings.pth file shape [27, 768]

**Comment by aiforworlds** [comment]
from clip import FrozenCLIPEmbedderContext
ImportError: cannot import name 'FrozenCLIPEmbedderContext' from 'clip' (c:\users\maker\src\clip\clip\__init__.py)

Another mistake is that you can't import  FrozenCLIPEmbedderContext from clip

**Comment by wl-zhao** [comment]
Hi, thanks for pointing out this. I have fixed the bug, could you try to rerun the script?
