### ISSUE TITLE
Depth Estimation with VPD

### ISSUE THREAD

**Issue by cvrookieytd** [wl-zhao/VPD#18]
Has anyone succeeded in replicating it? For convenient communication, you can leave a message

**Comment by oak-JHCheng** [comment]
I can't replicate the depth estimation result, maybe my batch size is too small that only 2. rms=0.264(vpd=0.254)

**Comment by wl-zhao** [comment]
Hi,
In our experiments, the global batch size of 24. Maybe you can try a larger batch size.

**Comment by Aradhye2002** [comment]
Is it normal to get the loss as nan for the first few 100 batches of ecoch 1?

**Comment by cvrookieytd** [comment]
> I can't replicate the depth estimation result, maybe my batch size is too small that only 2. rms=0.264(vpd=0.254)

In inference.yaml,
cond_stage_config:
target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
But in the LDM. Modules. The encoders. Modules
How did you solve the FrozenCLIPEmbedder function?

**Comment by cvrookieytd** [comment]
I haven't seen it yet. I haven't been paying attention。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wl-zhao/VPD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月26日(星期五) 凌晨1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wl-zhao/VPD] Depth Estimation with VPD (Issue #18)





 
Is it normal to get the loss as nan for the first few 100 batches of ecoch 1?

**Comment by wl-zhao** [comment]
This issue is closed since there has been no discussion for weeks. If there are any questions, please open a new issue.
