### ISSUE TITLE
mm versions for segmentation

### ISSUE THREAD

**Issue by nkondapa** [wl-zhao/VPD#19]
Hi thanks for sharing the code for your project.

I see in a previous issue you said you were using mmcv==1.7.1 and mmsegmentation==1.0.0, but the mmsegmentation==1.0.0 is the new version of the mm library and doesn't have the modules imported in segmentation/train.py. 
For example, the modules Config and DictAction have moved into mmengine.config module

Is it possible that you are using a different version of the libraries, or perhaps the train.py script is outdated?

**Comment by wl-zhao** [comment]
Sorry for the confusion. Please try mmcv-full==1.6.2 and mmsegmentation==0.30.0
