### ISSUE TITLE
Inconsistant configuration between the repo and the paper

### ISSUE THREAD

**Issue by FrontierBreaker** [wl-zhao/VPD#2]
Hi thanks for your wonderful jobs! However, I notice that the config for the semantic segmentation task is not consistent with the paper, thus I met with a failure in reproducing the numbers. 

Could you please provide the configs that are aligned with the configs in the main paper to foster the further research. 

Thanks~

**Comment by wl-zhao** [comment]
Hi, currently we have only released the checkpoint and the evaluation scripts. The training configuration will be released soon.

**Comment by wl-zhao** [comment]
This is just the config for evaluation. There are some differences between training/evaluation configs (lr and optimizer config)

**Comment by FrontierBreaker** [comment]
Got that, thanks~ Looking forward to the code release
