### ISSUE TITLE
Struggling to setup VPD

### ISSUE THREAD

**Issue by Sivloc** [wl-zhao/VPD#21]
Hi, I'm having trouble to run train.py - I want to run it without the train.sh file - , i have the following error : 
`
ModuleNotFoundError: No module named 'vpd.models'
`
Do you have any idea of what could be vausing this error ?
Also, just to be sure sure, is this supposed to be the correct structure ?
-/VPD
-----/checkpoints
---------v1-5-pruned.ckpt
-----/depth
-----/segmentation
-----etc...

**Comment by wl-zhao** [comment]
Hi,
In train.sh, we have already set the PYTHONPATH such that `vpd.models` can be found. We highly recommend using this script instead of directly running train.py.

**Comment by Sivloc** [comment]
Okay, thanks, and keep up the great work !
Before i close the issue, did you try to train the model with a limited number of GPUs ?

**Comment by wl-zhao** [comment]
We did not try to train VPD with limited resources since our main contribution is to reveal the power of generative pre-trained diffusion models. However, it would be an interesting future direction to investigate how to train a VPD more efficiently.
