### ISSUE TITLE
About class_embeddings

### ISSUE THREAD

**Issue by NorthSummer** [wl-zhao/VPD#22]
Hi, thanks for opening source VPD, and I want to ask about how to obtain the "class_embeddings.pth" of a specified new dataset? May I have to infer CLIP on that dataset every time I want to train VPD on a new dataset?

**Comment by wl-zhao** [comment]
Hi, the "class_embeddings.pth" is computed by extracting the text features of a sentence such as "a photo of a [CLASS LABEL]" using the CLIP. For each new dataset, we need to compute the class embeddings according to the labels of the dataset. Please refer to [this file](https://github.com/wl-zhao/VPD/blob/main/depth/dump_nyu_text_embeddings.py) for more details.

**Comment by NorthSummer** [comment]
Thanks! Very helpful~
