### ISSUE TITLE
Output Dim of Depth Estimation

### ISSUE THREAD

**Issue by agneet42** [wl-zhao/VPD#24]
Hi, I was wondering what would be the output dimension of the model here :
(https://github.com/wl-zhao/VPD/blob/main/depth/models_depth/model.py#L157)

Specifically, NYUv2 has 27 classes, does the count of the number of classes matter? My question arises from this part of the paper : Since the cross-attention maps are computed by using the conditioning inputs C as the key and value, the averaged attention map has the shape of |S|×H_{i}×W_{i}

**Comment by wl-zhao** [comment]
Hi,
As mentioned in the paper, we simply use a sentence describing the scene instead of feeding all the class names to the model for depth estimation. Besides, we didn't concatentate the cross-attention map for depth estimation because it only has one channel. Please refer to the code for details.
