### ISSUE TITLE
Loss calculation error during training

### ISSUE THREAD

**Issue by agneet42** [wl-zhao/VPD#25]
Hi @wl-zhao , I am following all the instructions mentioned here for training - https://github.com/wl-zhao/VPD/blob/main/depth/README.md
When I try to run the training script, I get an error, specifically in the loss function, https://github.com/wl-zhao/VPD/blob/main/depth/utils_depth/criterion.py#L17

`IndexError: The shape of the mask [3, 480, 480] at index 1 does not match the shape of the indexed tensor [3, 1, 480, 480] at index 1`
The error makes sense since pred.shape is [3, 1, 480, 480] & gt.shape is [3, 480, 480].

I can fix it by squeezing dim=1 instead, at https://github.com/wl-zhao/VPD/blob/main/depth/train.py#L228. 

However, I want to confirm if this is the right change or am I missing something? The only config change I have made is updating the num_workers for the dataloader, but that should not impact anything.

**Comment by wl-zhao** [comment]
Hi, thanks for pointing out this! It is caused by a bug in a previous pull request. I have already fixed it.
