### ISSUE TITLE
Failed to reproduce the accuracy on ADE20k

### ISSUE THREAD

**Issue by Ben-Louis** [wl-zhao/VPD#32]
Hello, thanks for your excellent work! At the moment, I am in the process of training a segmentation model on ADE20k utilizing the configuration you have provided. However, the final mIoU I have achieved is 53.1, which is lower than the reported 53.7. I have included my [log](https://github.com/wl-zhao/VPD/files/12331215/20230813_162255.log.json.txt). Is there any advice you could provide on how to improve my training process? Thank you.

**Comment by wl-zhao** [comment]
Please refer to [this issue](https://github.com/wl-zhao/VPD/issues/23#issuecomment-1656703235) for our training log. Maybe you can have another check of the environment information and the hyperparameters.

**Comment by Ben-Louis** [comment]
I used the config file provided and made no modifications to ensure identical hyperparameters. 
Additionally, I use mmcv==1.6 and mmseg==0.30.0, matching your training log.
