### ISSUE TITLE
FPN head

### ISSUE THREAD

**Issue by elhamAm** [wl-zhao/VPD#36]
Hello!

How does the FPN head not have feature strides? The init of FPNHead in mmseg requires feature_strides
https://github.com/wl-zhao/VPD/blob/90c9d85933306a9bc4d5eae395f25c512041d359/segmentation/configs/fpn_vpd_sd1-5_512x512_gpu8x2.py#L14

**Comment by wl-zhao** [comment]
Hi,
The parameters in this config file are inherited from the base config file ([here](https://github.com/wl-zhao/VPD/blob/90c9d85933306a9bc4d5eae395f25c512041d359/segmentation/configs/fpn_vpd_sd1-5_512x512_gpu8x2.py#L2)), where the feature strides are set as `feature_strides=[4, 8, 16, 32]`.
