### ISSUE TITLE
will you release the code of diffswap?

### ISSUE THREAD

**Issue by vicentowang** [wl-zhao/VPD#38]

**Comment by kagevazquez** [comment]
and if not would it be impossible to make a huggingface space for this project? Getting the depth estimation alone into peoples hands would get more eyes on all of your research. It deserves the recognition.

**Comment by wl-zhao** [comment]
Hi, 
Thanks for your interest in our work. I am actually planning to release the code of DiffSwap. However, I have been really busy in the last few months (NeurIPS submission, ICCV rebuttal, NeurIPS rebuttal, etc). Now I finally have some time and I think the code of DiffSwap will be ready in a week.

**Comment by niuyuanc** [comment]
looking forward to the code of DiffSwap
