### ISSUE TITLE
Can you describe the inferance process? 

### ISSUE THREAD

**Issue by robinggong** [wl-zhao/VPD#4]
Can you describe the inference process?  or Can you provide a script for inference?

**Comment by wl-zhao** [comment]
Hi, the inference scripts have been provided in the subfolders of the three tasks. Please refer to [segmentation.md](https://github.com/wl-zhao/VPD/blob/main/segmentation/README.md), [refer.md](https://github.com/wl-zhao/VPD/blob/main/refer/README.md) and [depth.md](https://github.com/wl-zhao/VPD/blob/main/depth/README.md) for details.

**Comment by robinggong** [comment]
Thanks
