### ISSUE TITLE
What does A32/A64 mean?

### ISSUE THREAD

**Issue by Vincent-luo** [wl-zhao/VPD#6]
When using VPD for semantic segmentation, does A32/A64 mean that only use size 32/64 attention maps? In the source code, attn16, attn32, attn64 are all used, how can i reproduce the results of VPD_A32 and VPD_A64?

**Comment by wl-zhao** [comment]
Thanks for your interest in our work! A32 means attn16+attn32 are used and attn64 means attn16+attn32+attn64 are used. A64 is used by default and you can set max_attn_size=32 to the UNetWrapper to enable A32.

**Comment by Vincent-luo** [comment]
Thanks for your reply! I'll try it.
