### ISSUE TITLE
Class embedding

### ISSUE THREAD

**Issue by SnowdenLee** [wl-zhao/VPD#8]
Hi, 
thanks for the interesting work! Could you please also share the code for creating the class embedding, so that I could try on my own dataset? 
More specifically, the text embedding for one prompt has a shape of [77, 768]. However, in the class_embedding.pt, each class only has an embedding with shape of [1,768]. Did you average over 77 tokens or?
Thanks a lot!

**Comment by wl-zhao** [comment]
Hi,

Please refer to the [FrozenCLIPEmbedder](https://github.com/wl-zhao/VPD/blob/3d503c2d4748b28b1cfc2688de2ea53edc1d6aa5/vpd/models.py#L309), where we use `pool=True` to obtain the embedding for each class.

Feel free to ask if you have any questions!

**Comment by elhamAm** [comment]
hi !
thanks for the great work,
in the original stable diffusion, this pooling does not exist so I am wondering what is the point of using pretrained weights if you are changing the prompt embeddings to a pooled version?
