### ISSUE TITLE
Inconsistent Training images number for NYUv2 in the preprint

### ISSUE THREAD

**Issue by praeclarumjj3** [wl-zhao/VPD#9]
Hi, thanks for your work.

Please correct me if I am wrong, but the number of training images for the NYUv2 dataset is mentioned as `24k` in your preprint. However, the original NYUv2 dataset, as well as the NYUv2 dataset prepared using your instructions, have only 795 images. Do you use any extra training data, or is it just a typo in the paper? Thanks

<img width="528" alt="Screenshot 2023-03-26 at 10 03 10 PM" src="https://user-images.githubusercontent.com/54928629/227790217-42e08a20-b091-4db3-adec-0014eea2472a.png">

**Comment by liuzuyan** [comment]
Hi, thanks for your interest in our work. 
We follow the experimental settings in [GLPDepth](https://github.com/vinvino02/GLPDepth) and [MIM-Depth-Estimation](https://github.com/SwinTransformer/MIM-Depth-Estimation) for depth estimation training. All of them train the models on 24k images.

**Comment by liuzuyan** [comment]
The file list of training and testing images can be found at [this url](https://github.com/wl-zhao/VPD/tree/main/depth/dataset/filenames/nyudepthv2). You can follow the instructions in [README.md](https://github.com/wl-zhao/VPD/blob/main/depth/README.md) to download NYUDepthV2 and sync.zip for full datasets.

**Comment by praeclarumjj3** [comment]
Thanks for the clarification!
